### ISSUE TITLE
improvements (css, js ...)

### ISSUE THREAD

**Issue by DanielRuf** [frapi/frapi#115]
We should upgrade jquery to the latest version and all other scripts
And use twitter bootstrap
Use datatables instead of tablesorter?

**Comment by dshafik** [comment]
Care to justify your reasoning? This seems like pointless work at this stage in FRAPIs life-cycle... Patches welcome, of course

**Comment by DanielRuf** [comment]
Well, the latest jQuery should be much better and also faster for the backend.

Also I hope to see a more modern backend (made with twitter bootstrap?)

And what I wanted to know:
Is there something for the partners like a dashboard with statistics (requests per month, day ...)
What about rate limiting in the admin backend?

Also datatables works well with the latest jquery version but tablesorter not (and has some issues)

**Comment by davidcoallier** [comment]
I'd be more than delighted to have a patch for this :-) If you feel like making some quick mockups and showing what you have in mind that'd be lovely :-)

**Comment by arski** [comment]
ooh, access statistics and rate limiting.. would loove to have that :) Might contribute something if I figure out how things work here more exactly (used to Drupal's hook-oriented dev, not OO :))

**Comment by DanielRuf** [comment]
Well I use currently also drupal services module but need frapi with these features for some non drupal projects =)

**Comment by arski** [comment]
Hehe, I moved away from Drupal Services for my current project because it just didn't scale, going through the Drupal stack every time.. awful..

We could split up on these two topics: I could take a look at rate limiting and maybe you could do some usage reporting. One thing I wonder about, is it possible at all to limit requests to a certain host when using AJAX? So I'm running a JS widget on 3rd party sites that access my IP.. obviously the AJAX call comes from the user's browser, so I can't limit by IP of the host site.. what is the common practice there to prevent resource hijacking so to say?

Cheers

**Comment by dshafik** [comment]
@arski You can't request anything but the same-domain with AJAX, so the request would not be going directly from the browser to your API, but instead from the browser to the host, to you (which is also required if the host site has credentials for them, and not for the user). That would be one IP.

Having said that; limit based on api keys, not IPs, IPs can (and will) change.

The biggest issue with rate-limiting, is tracking it. The tracking/checking, needs to be fast, but at least somewhat persistent. You could throw it in memcache (or similar), or (so as not to introduce a new dependency for frapi) apc, but that means if you restart either memcache or your webserver, users limits reset back to 0. I would consider MySQL (or your DB of choice) too slow, except you're likely already using the DB for the request...

A more important part of the story, instead of rate-limiting, is caching. Better caching, and more responsible clients (sending correct If-Modified-Since, etc), is the best option for performance vs functionality, IMO.

**Comment by arski** [comment]
Hmm, I just checked the access logs on my API's server, and I'm seeing that the requests are actually coming from the user and not the host site. Just to make the example clearer:
user A accesses site www.testsite.com where there is a .js script executing an .ajax POST call to api.frapihost.com that fetches some data to display. When looking at the access logs on frapihost.com, I see that the request came from the user's IP (mine), not the www.testsite.com's URL, as you suggested would be the case, if I understood correctly.

And indeed, I was just wondering about that in order to maybe restrict API calls to a set of IPs, not connected to the rate limit discussion. 

And yea, I don't think storing the rate usage in cache will work.. it needs something more persistent like MySQL or whatever FRAPI is using now to store different config details (?).

**Comment by dshafik** [comment]
@arski You might want to check your Javascript, it is likely doing `jsonp`.

For more info check the [same origin policy article on wikipedia](http://en.wikipedia.org/wiki/Same_origin_policy).

As far as using the frapi config storage mechanism, it's slow (XML based), that is cached in APC... so it wouldn't work for this.

I wouldn't want to make MySQL (or any DB) a requirement for frapi. The best option here is to provide an easy mechanism to hook your own code into to determine the rate-limits and handle storage.

**Comment by DanielRuf** [comment]
JSON would be much faster? Scaling Drupal is not the problem but your hosting environment.
I would go away from xml based files and use the much better json structure.

**Comment by arski** [comment]
@dshafik I've started looking into jsonp, but atm I'm still using jquery's ajax - apparently it works because I have "Allow cross domain requests" checked in my FRAPI config.

I'll take a look at maybe creating some mysql-based adapter for rate limiting, I was quite sure you wouldn't want frapi to be dependent on MySQL as you said.

@DanielRuf isn't that the same really - Drupal just eats up too many resources and services doesn't currently support a light bootstrap mode to make it quicker (plus it gets slowed down by the menu lookup and a bunch of other things) There's a rather tentative discussion about all that going on in http://drupal.org/node/218360

**Comment by DanielRuf** [comment]
Well I optimized Drupal in some ways and use also cloudflare (with caching ...) and it is much faster

**Comment by arski** [comment]
hehe cool, did you by any chance run comparisons of same API function between services and frapi? For me, using drupal services, it took the server about 1s per request, while with frapi around 0.1s - though I have to admit my Drupal installation was not optimized at all. Anyway, getting off topic a bit here ;)

Do you think you'll have time sometime soon to look at showing usage statistics etc? I guess that would also need to be stored persistently somehow, possibly in a mysql access log.. so maybe we should work out some sort of add-on architecture for things like these first.

**Comment by dshafik** [comment]
As this ticket is not actionable (too broad), and has turned into a discussion on other matters, I am closing it. 

However, I am also [slowly] working through a [review of the UI/UX](https://github.com/frapi/frapi/wiki/UI-UX-Review) — please feel free to open tickets if you wish to discuss the contents. Eventually, it will result in actionable tickets, however I don't expect this to go into the current release.

**Comment by DanielRuf** [comment]
I saw you use then twitter bootstrap for the new UI? Looks great what I saw already =)
