### ISSUE TITLE
Why src/frapi ?

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#164]
Hello !

It's not an issue, just a question.

I have many projects based on the amazing frapi. My other projects are also on github, and I have to confess that the path src/frapi for all my projects, makes them a little messy.

Here is my question: Why did you commit your project with src/frapi/[content] instead of just [content] then when cloning, it wouldn't create "project/src/frapi/[content]" but just "project/[content]".

Just a question.
Thank you.

PS: I know that I can just remove the path and move the "[content]" to a good place for me, but I'm loosing the ability to directly merge frapi/frapi to my project (to get the updates)

**Comment by davidcoallier** [comment]
Hey there :) 

So the reason is because in an attempt to become PSR-1 compliant, we have the src directory which should only contain "code". We have to move the tets, docs, and whatnot out of the src/frapi directory soon in order to be able to move ahead with this. 

It's basically to help with distribution of code where tools would install what's in `src` but not everything else. In our case, everything is in `src` which invalidates the concept however it is planned that one day FRAPI will get cleaned up ;)

**Comment by Max13** [comment]
Okay... I get it.
You're not the one who has to answer me, but is there a way to clone a subdirectory of a project ?

If it's not possible... I'll have to make symlink and to clone frapi to only 1 directory.
Thanks.

**Comment by davidcoallier** [comment]
Unfortunately that's not possible with older versions of Git, however since Git 1.7.0 there's something called "Sparse Checkouts" which you can find more about here: http://jasonkarns.com/blog/subdirectory-checkouts-with-git-sparse-checkout/

**Comment by Max13** [comment]
Thank you.
