### ISSUE TITLE
(Code Could not connect) via TCP???

### ISSUE THREAD

**Issue by ajtrichards** [frapi/frapi#60]
I've created the API and it works fine if i open it in a separate browser window - however if i use the Tester part of FRAPI Admin I get an error saying:

Error: Unable to connect to
    tcp://api.WEBSITEURL.co.uk:80. Error
    #10060: A connection attempt failed because
    the connected party did not properly respond
    after a period of time, or established
    connection failed because connected host has
    failed to respond.

I get a similar message if I add my database credentials to the config. If i manually add mysql_connect('host', 'user', 'pass') to my code file it works fine.

Is this error caused by my setup or FRAPI?

**Comment by davidcoallier** [comment]
You  need to configure your API url in the /configuration page of the Admin so it knows where your API is.

**Comment by ajtrichards** [comment]
Hi david,

This is already configured.

Cheers
------Original Message------

**Comment by davidcoallier** [comment]
Oh wait, you are connecting using "tcp://", why not "http://"? 

Also, what's your version of PHP and webserver you are running.

**Comment by ajtrichards** [comment]
Yeah that's the weird thing - why TCP instead of HTTP?

Webserver is Apache 2.2.17 and PHP 5.3.5

**Comment by davidcoallier** [comment]
Is this happening from the Tester or from some other source?

## 

David Coallier, CTO echolibre, +353 86 3209369
skype://david.coallier, @davidcoallier

**Comment by ajtrichards** [comment]
I just downloaded frapi from the download link and followed the install instructions.
------Original Message------

**Comment by davidcoallier** [comment]
Ok, did you download latest.tar.gz or the "tar.gz" besides the ".zip" file?

**Comment by ajtrichards** [comment]
I think it was the ZIP file. 
------Original Message------

**Comment by davidcoallier** [comment]
This is very odd. What's the exact value you put in the API Url in the /configuration screen? Just the hostname without http://?

**Comment by ajtrichards** [comment]
Yes hostname without http. Shall I try with http?
------Original Message------

**Comment by davidcoallier** [comment]
Nah it should be only the hostname. This is quite odd. Have you tried restarting the web-server since you've set it up originally? 

I also recommend you use a githug checkout. If you've did this checkout a few days ago there might be some caching issues I've committed yesterday with multiple servers. That could be it.

**Comment by ajtrichards** [comment]
I've restarted web server and o/s. Ill uninstall and reinstall all again and see what happens.
------Original Message------

**Comment by davidcoallier** [comment]
Very sorry about this.

**Comment by ajtrichards** [comment]
Hey no problem - I think FRAPI's great. I've installed before but this was a new server so I thought there may have been something that had changed in one of the commits.

Cheers
------Original Message------

**Comment by davidcoallier** [comment]
Is it better now? Did you manage to get it running correctly?

**Comment by bruce-gemberling** [comment]
I have the exact same issue:

Error: Unable to connect to tcp://api.frapi:80.
    Error: php_network_getaddresses: getaddrinfo
    failed: Name or service not known

**Comment by davidcoallier** [comment]
This is fairly odd, what is your setup?

What if you do

```
curl -v http://api.frapi
```

Do you get a response from that?

**Comment by bruce-gemberling** [comment]
David,

I am trying it from the tester in the admin area.

I cloned frapi with git on Centos5.5, PHP 5.3, Apache 2.0.

I've grepped for "tcp" and found a few files in the library/Zend sub directories but changing these to use "http" has no effect.

My problem is that the "Run Test" always uses tcp://api.frapi:80 instead of http://api.frapi. I contacted ajtrichards and they said they never resolved the issue either.

I have gotomeeting. Do you think you could jump on that real quick with me so I could show you?

**Comment by bruce-gemberling** [comment]
David,

I am trying it from the tester in the admin area.

I cloned frapi with git on Centos5.5, PHP 5.3, Apache 2.0.

I've grepped for "tcp" and found a few files in the library/Zend sub
directories but changing these to use "http" has no effect.

My problem is that the "Run Test" always uses tcp://api.frapi:80 instead of
http://api.frapi. I contacted that ajtrichards fellow and he said he never
resolved the issue either.

I have gotomeeting. Do you think you could jump on that real quick with me
so I could show you?

Thank you,

---

   Bruce Gemberling          Web Developer

##    Sugar Land, TX              (713) 234-0582

**Comment by bruce-gemberling** [comment]
C:\Users\bruce>curl -v http://api.frapi
- About to connect() to api.frapi port 80 (#0)
-   Trying 127.0.0.1... connected
- Connected to api.frapi (127.0.0.1) port 80 (#0)
  > GET / HTTP/1.1
  > User-Agent: curl/7.21.6 (i386-pc-win32) libcurl/7.21.6 zlib/1.2.5
  > Host: api.frapi
  > Accept: _/_
  >
  < HTTP/1.1 404 Not Found
  < Date: Wed, 22 Jun 2011 20:24:42 GMT
  < Server: Apache/2.0.63 (Unix) mod_ssl/2.0.63 OpenSSL/0.9.8e-fips-rhel5 mod_auth
  _passthrough/2.1 mod_bwlimited/1.4 FrontPage/5.0.2.2635 PHP/5.3.6
  < X-Powered-By: PHP/5.3.6
  < Access-Control-Allow-Origin: *
  < Access-Control-Allow-Headers: *
  < Access-Control-Allow-Credentials: true
  < Access-Control-Allow-Methods: POST,GET,PUT,DELETE,HEAD
  < Access-Control-Max-Age: 604800
  < Content-Length: 283
  < Content-Type: application/xml; charset=utf-8
  <
  <?xml version="1.0" encoding="UTF-8"?>
  <response>
  <errors>    <error code="ERROR_INVALID_ACTION_REQUEST">
          <message>Invalid requested action</message>
          <name>ERROR_INVALID_ACTION_REQUEST</name>
          <at></at>
      </error>
  </errors>

</response>
- Connection #0 to host api.frapi left intact
- Closing connection #0

**Comment by djungowski** [comment]
I am having the exact same problem when using the tester. I cloned the latest version from Github and settings are default.

Error: Unable to connect to tcp://api.frapi:8080.
Error: php_network_getaddresses: getaddrinfo
failed: Name or service not known

**Comment by djungowski** [comment]
Also, I don't understand why this has been closed w/o a solution?

**Comment by bruce-gemberling** [comment]
My issue was that I was using a development box at home with a fake url and
the box didn't resolve the fake url in it's own /etc/hosts file. Once I put
the fake url in the /etc/hosts file it worked fine.

Thank you,

---

   Bruce Gemberling          Web Developer

##    Sugar Land, TX              (713) 234-0582

On Sun, Dec 4, 2011 at 8:36 AM, Dominik Jungowski <
reply@reply.github.com

**Comment by djungowski** [comment]
Nice, I just wanted to write the same thing :D

My Frapi is running on a virtual machine an api.frapi is in my /etc/hosts directing to the virtual machine. Once I modified the hosts file of the virtual machine aswell, adding 127.0.0.1 api.frapi, it worked fine.

**Comment by mirlo06** [comment]
hi ,
What is the request to invoke a web service Frapi in android  ?? i try with ttp://api.frapi/login  but no answer
